# Generated by Django 4.1 on 2022-09-03 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generalvalidations.database_validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[generalvalidations.database_validations.characters_size_should_be_grater_than_two, generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.should_not_have_special_characters])),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sell.paymenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
