# Generated by Django 4.1 on 2022-09-04 01:24

from django.db import migrations, models
import generalvalidations.database_validations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[generalvalidations.database_validations.characters_size_should_be_grater_than_two, generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.should_not_have_special_characters]),
        ),
    ]
