# Generated by Django 4.1 on 2022-08-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=70)),
                ('identification_number', models.CharField(max_length=20)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.identificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='inventary/picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.category')),
                ('state_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.stateproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.supplier')),
            ],
        ),
    ]
