# Generated by Django 4.1 on 2022-09-03 21:14

from django.db import migrations, models
import django.db.models.deletion
import generalvalidations.database_validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.category_size_should_be_greater_than_four, generalvalidations.database_validations.should_not_have_special_characters])),
            ],
        ),
        migrations.CreateModel(
            name='StateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=12, unique=True, validators=[generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.state_product_should_be_greater_than_four, generalvalidations.database_validations.should_not_have_special_characters, generalvalidations.database_validations.should_not_have_spaces])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[generalvalidations.database_validations.characters_size_should_be_grater_than_two])),
                ('email', models.EmailField(max_length=155, unique=True)),
                ('cellphone', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.cellphone_number_size_is_ten])),
                ('address', models.CharField(max_length=200)),
                ('identification_number', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.identification_number_size_should_be_greater_than_seven])),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.identificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[generalvalidations.database_validations.characters_size_should_be_grater_than_two])),
                ('description', models.CharField(max_length=255)),
                ('price_by_unity', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('warranty', models.IntegerField()),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='inventary/picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.category')),
                ('state_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.stateproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventary.supplier')),
            ],
        ),
    ]
