# Generated by Django 4.1 on 2022-09-03 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generalvalidations.database_validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, unique=True, validators=[generalvalidations.database_validations.characters_size_should_be_grater_than_two, generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.should_not_have_spaces])),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.cellphone_number_size_is_ten])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/picture')),
                ('identification_number', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.identification_number_size_should_be_greater_than_seven])),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.identificationtype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.characters_size_should_be_grater_than_two, generalvalidations.database_validations.should_not_have_special_characters])),
                ('last_name', models.CharField(max_length=50, validators=[generalvalidations.database_validations.should_be_alphabetic, generalvalidations.database_validations.characters_size_should_be_grater_than_two, generalvalidations.database_validations.should_not_have_special_characters])),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.cellphone_number_size_is_ten])),
                ('identification_number', models.CharField(max_length=10, validators=[generalvalidations.database_validations.is_number, generalvalidations.database_validations.identification_number_size_should_be_greater_than_seven])),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.identificationtype')),
            ],
        ),
    ]
